import "dotenv/config";
// Load the ethers plugin via side-effect import (Hardhat v3)
import "@nomicfoundation/hardhat-ethers";

const DIDLAB_RPC = process.env.DIDLAB_RPC_URL || process.env.RPC_URL || "https://eth.didlab.org";
const RAW_DIDLAB_KEY =
  process.env.DIDLAB_DEPLOYER_KEY ||
  process.env.DIDLAB_KEY ||
  process.env.DEPLOYER_KEY ||
  "";
const DIDLAB_KEY =
  RAW_DIDLAB_KEY && RAW_DIDLAB_KEY.startsWith("0x")
    ? RAW_DIDLAB_KEY
    : RAW_DIDLAB_KEY
    ? `0x${RAW_DIDLAB_KEY}`
    : "";

const SOLIDITY = {
  version: "0.8.24",
  settings: {
    /**
     * DIDLab nodes have not enabled Shanghai/PUSH0 opcodes yet,
     * so forcing the Paris EVM keeps generated bytecode compatible.
     */
    evmVersion: "paris",
    optimizer: { enabled: true, runs: 200 },
  },
};

export default {
  solidity: SOLIDITY,
  networks: {
    hardhat: { type: "edr-simulated", chainId: 31337 },
    localhost: { type: "http", url: "http://100.114.157.9:8545", chainId: 31337 },
    didlab: {
      type: "http",
      url: DIDLAB_RPC,
      chainId: 252501,
      accounts: DIDLAB_KEY ? [DIDLAB_KEY] : undefined,
    },
  },
};
